// src/components/ui/atoms/AboutSecondary.svelte
<script lang="ts">
	import type { ScrollAnimationStyle } from '$lib/types';
	import ScrollObserver from '../../misc/ScrollObserver.svelte';

	const animation: ScrollAnimationStyle = {
		onHidden: ['scale-90', 'opacity-0'],
		onVisible: ['scale-100', 'opacity-100']
	};
</script>

<ScrollObserver scrollAnimation={animation} className="xl:px-12">
	<h1 class="text-neutral-300 text-[clamp(0.5rem,2vw,1rem)]">
		I aim to create elegant and responsive websites for multiple purposes, like blogs and promotional pages.
	</h1>
	<br />
	<h1 class="text-red-400 text-[clamp(0.5rem,2vw,1rem)]">
		I also work with web apps involving data analysis using relational and non-relational databases.
	</h1>
</ScrollObserver>

// src/components/ui/atoms/AboutSecondary.tsx
import ScrollObserver from '@/components/misc/ScrollObserver';
import { scrollAnimationStyle } from '@/constants/types';

const animation: scrollAnimationStyle = {
	onHidden: ['scale-90', 'opacity-0'],
	onVisible: ['scale-100', 'opacity-100'],
};

export default function AboutSecondary() {
	return (
		<ScrollObserver scrollAnimation={animation} className='xl:px-12'>
			<h1 className='text-neutral-300 text-[clamp(0.5rem,2vw,1rem)]'>
				I aim to create elegant and responsive websites for multiple purposes, like blogs and promotional pages.
			</h1>
			<br />
			<h1 className='text-red-400 text-[clamp(0.5rem,2vw,1rem)]'>
				I also work with web apps involving data analysis using relaitonal and non-relational databases.
			</h1>
		</ScrollObserver>
	);
}
