// src/components/ui/molecules/LinksList.svelte
<script lang="ts">
	import { LinksListItems } from '../../../constants/objects/LinksListItems';
	import type { ScrollObserverTransition } from '../../../constants/types/types';
	import ScrollObserver from '../../misc/ScrollObserver.svelte';
	import LinksListItem from '../atoms/LinksListItem.svelte';

	const transition: ScrollObserverTransition = {
		onHidden: ['translate-x-8', 'opacity-0'],
		onVisible: ['translate-x-0', 'opacity-100']
	};
</script>

<ScrollObserver {transition} className="my-auto flex flex-col items-center lg:gap-12 gap-4">
	<h1 class="text-center text-neutral-200">Let's Connect!</h1>
	<div class="lg:w-full w-max flex lg:flex-row flex-col justify-center items-center lg:gap-12">
		{#each LinksListItems as item}
			<LinksListItem {...item} />
		{/each}
	</div>
</ScrollObserver>

// src/components/ui/molecules/LinksList.tsx
import ScrollObserver from '@/components/misc/ScrollObserver';
import { linksListItems } from '@/constants/objects/LinksListItems';
import { scrollAnimationStyle } from '@/constants/types';
import ListItem from '../atoms/ListItem';

const animation: scrollAnimationStyle = {
	onHidden: ['-translate-x-8', 'opacity-0'],
	onVisible: ['-translate-x-0', 'opacity-100'],
};

export default function LinksList() {
	return (
		<ScrollObserver
			className='w-full flex lg:flex-row flex-col justify-center items-center gap-8'
			scrollAnimation={animation}>
			{linksListItems.map((item, index) => (
				<ListItem {...item} key={index} />
			))}
		</ScrollObserver>
	);
}
