// src/components/ui/organisms/About.svelte
<script>
	import { scrollRef } from '$lib/utils/scroll';
	import AboutIntro from '../atoms/AboutIntro.svelte';
	import AboutPrimary from '../atoms/AboutPrimary.svelte';
	import AboutSecondary from '../atoms/AboutSecondary.svelte';
	import AboutIcons from '../molecules/AboutIcons.svelte';
</script>

<section use:scrollRef={'About'} class="overflow-hidden xl:px-12 px-4 py-12 flex flex-col gap-12">
	<AboutIntro />
	<AboutPrimary />
	<AboutIcons />
	<AboutSecondary />
</section>

// src/components/ui/organisms/About.tsx
import { Element } from '@/constants/react-scroll';
import AboutIntro from '../atoms/AboutIntro';
import AboutPrimary from '../atoms/AboutPrimary';
import AboutSecondary from '../atoms/AboutSecondary';
import AboutIcons from '../molecules/AboutIcons';

export default function About() {
	return (
		<Element name='About' className='overflow-hidden xl:px-12 px-4 py-12 flex flex-col gap-12'>
			<AboutIntro />
			<AboutPrimary />
			<AboutIcons />
			<AboutSecondary />
		</Element>
	);
}
